name: Auto Merge to Main

on:
  push:
    branches:
      - staging

jobs:
  merge_to_main:
    runs-on: ubuntu-latest
    env:
        GIT_USER_EMAIL: ${{ github.event.owner.email }}
        GIT_USER_NAME: ${{ github.actor }}
    steps:
      - name: Set Git config
        run: |
          git config --global user.email "${GIT_USER_EMAIL}"
          git config --global user.name "${GIT_USER_NAME}"

      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: 'main'
          fetch-depth: 0

      - name: Merge staging into main
        run: git merge --no-ff origin/staging -m "Auto-merge staging to main"

      - name: Push changes to main
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: main
